### ISSUE TITLE
Couldn't resolve host 'repo.zabbix.com'

### ISSUE THREAD

**Issue by itshemant4u** [dkanbier/docker-zabbix-server#4]
Complete error:
http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 6 - "Couldn't resolve host 'repo.zabbix.com'"
Trying other mirror.
## Reason: Firewall blocking access to repo.zabbix.com

My Resolution: Manually download /repodata from http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/
Now, in "repomd.xml" I am updating the location href= "/repodata//other.xml.gz"  as below
  < location > ./repodata/other.xml.gz> < /location >

However, I still keep getting the same error
My question is how can i make sure that the dockerfile shouldn't go to the internet('repo.zabbix.com') to get other.xml.gz I want to make sure that the other.xml.gz file is taken from the local downloaded /repodata directory.

**Comment by dkanbier** [comment]
As internet acces is kind of a requirement for this Dockerfile to work properly I can't really solve this issue with a code update.

You could do an offline installation, and I think the command you're looking for is `createrepo`.

For example, if you've mirrored the contents of http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64 to /home/me/zabbix you can run:

```
$ cd /home/me/zabbix
$ createrepo . 
```

This will update the zabbix/repodata directory with the appropriate values.

I'm closing this as an issues as it's not something I can fix on my end, but feel free to keep me posted here or by mail if you need an extra hand.
